from datetime import date, datetime
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from core.constants import ACCENT_RED, PRIMARY_COLOR, SECONDARY_COLOR
from ticket.enums import Priority


class TicketReportPDF:
    """
    This class handles the heavy lifting of turning our ticket data into
    a clean, landscape PDF. It builds a few summary tables first,
    followed by a big list of every ticket we've tracked.
    """

    def __init__(self, data):
        self.report_data = data.get("data", data) if isinstance(data, dict) else data
        self.buffer = BytesIO()
        self.styles = getSampleStyleSheet()
        self._setup_styles()

    def _setup_styles(self):
        """Sets up how our headers and metadata text should look."""
        self.header_style = ParagraphStyle(
            "SectionHeader",
            parent=self.styles["Heading2"],
            fontSize=12,
            textColor=PRIMARY_COLOR,
            spaceBefore=10,
            spaceAfter=8,
        )
        self.meta_style = ParagraphStyle(
            "Meta",
            fontSize=9,
            textColor=colors.grey,
            leading=12,
        )

    def _apply_theme(self, font_size=8):
        """A reusable style for our tables to keep the blue branding consistent."""
        return TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), PRIMARY_COLOR),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), font_size),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, SECONDARY_COLOR]),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]
        )

    def generate(self):
        """
        The main engine that assembles the PDF sections.
        Returns a buffer that the view can send back to the user.
        """
        doc = SimpleDocTemplate(
            self.buffer,
            pagesize=landscape(A4),
            rightMargin=20,
            leftMargin=20,
            topMargin=20,
            bottomMargin=20,
        )
        elements = []
        p_labels = [p.label for p in Priority]

        elements.append(Paragraph("Ticket Intelligence Report", self.styles["Title"]))
        meta = self.report_data.get("metadata", {})
        if meta:
            meta_text = (
                f"<b>Project:</b> {meta.get('project_title')} | "
                f"<b>Period:</b> {meta.get('date_range')} | "
                f"<b>Generated By:</b> {meta.get('generated_by')}"
            )
            elements.append(Paragraph(meta_text, self.meta_style))
        elements.append(Spacer(1, 15))

        elements.append(
            Paragraph("1 & 2. Status and Priority Distribution", self.header_style)
        )

        status_rows = [["Status", "Count"]] + [
            [i["name"], i["count"]] for i in self.report_data.get("status_stats", [])
        ]
        t_status = Table(status_rows, colWidths=[1.4 * inch, 0.7 * inch])
        t_status.setStyle(self._apply_theme())

        priority_rows = [["Priority", "Count"]] + [
            [i["name"], i["count"]] for i in self.report_data.get("priority_stats", [])
        ]
        t_priority = Table(priority_rows, colWidths=[1.4 * inch, 0.7 * inch])
        t_priority.setStyle(self._apply_theme())

        combined_data = [[t_status, Spacer(0.2 * inch, 0), t_priority]]
        container_table = Table(
            combined_data, hAlign="LEFT", colWidths=[2.2 * inch, 0.2 * inch, 2.2 * inch]
        )
        container_table.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP")]))

        elements.append(container_table)
        elements.append(Spacer(1, 20))

        elements.append(
            Paragraph("3. Efficiency & Completion Metrics", self.header_style)
        )
        eff_rows = [["Metric"] + p_labels]
        for item in self.report_data.get("efficiency_stats", []):
            eff_rows.append(
                [item["label"]] + [item.get(label, 0) for label in p_labels]
            )
        t_eff = Table(
            eff_rows,
            hAlign="LEFT",
            colWidths=[1.8 * inch] + [0.8 * inch] * len(p_labels),
        )
        t_eff.setStyle(self._apply_theme())
        elements.append(t_eff)
        elements.append(Spacer(1, 20))

        timeline = self.report_data.get("timeline_stats", [])
        if timeline:
            elements.append(
                Paragraph("4. Historical Timeline Trends", self.header_style)
            )
            time_rows = [["Period"] + p_labels]
            for item in timeline:
                time_rows.append(
                    [item.get("label")] + [item.get(label, 0) for label in p_labels]
                )
            t_time = Table(
                time_rows,
                hAlign="LEFT",
                colWidths=[1.2 * inch] + [0.8 * inch] * len(p_labels),
            )
            t_time.setStyle(self._apply_theme())
            elements.append(t_time)

        tickets = self.report_data.get("detailed_tickets", [])
        if tickets:
            elements.append(PageBreak())
            elements.append(
                Paragraph("5. Detailed Ticket Inventory", self.header_style)
            )

            header = [
                "Ticket Name",
                "Project",
                "Jira ID",
                "Status",
                "Assignee Email",
                "Reporter Email",
                "Updated At",
                "Spilled",
            ]
            rows = [header]

            for t in tickets:
                updated = (
                    t["updated_at"].strftime("%Y-%m-%d")
                    if isinstance(t["updated_at"], (date, datetime))
                    else "N/A"
                )
                rows.append(
                    [
                        (t["name"][:30] + "..") if len(t["name"]) > 30 else t["name"],
                        t.get("project_title", "All Projects")[:15],
                        t.get("jira_id"),
                        t.get("status"),
                        t.get("assignee_email") or "N/A",
                        t.get("reporter_email") or "N/A",
                        updated,
                        "YES" if t.get("is_spilled") else "No",
                    ]
                )

            t_detail = Table(
                rows,
                repeatRows=1,
                colWidths=[
                    1.8 * inch,
                    1.2 * inch,
                    0.8 * inch,
                    0.9 * inch,
                    1.8 * inch,
                    1.8 * inch,
                    1 * inch,
                    0.7 * inch,
                ],
            )

            detail_style = self._apply_theme(font_size=7)
            for i, row in enumerate(rows):
                if row[7] == "YES":
                    detail_style.add("TEXTCOLOR", (7, i), (7, i), ACCENT_RED)
                    detail_style.add("FONTNAME", (7, i), (7, i), "Helvetica-Bold")

            t_detail.setStyle(detail_style)
            elements.append(t_detail)

        doc.build(elements)
        self.buffer.seek(0)
        return self.buffer
