# Generated by Django 4.2.28 on 2026-03-27 10:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectModel',
            new_name='Project',
        ),
    ]
