# Generated by Django 4.2.28 on 2026-03-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectinvitation',
            name='unique_active_invite_per_project_invitee',
        ),
        migrations.AddConstraint(
            model_name='projectinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('project', 'invitee', 'is_deleted'), name='unique_active_invite_per_project_invitee', violation_error_message='An active invitation already exists'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_membership', violation_error_message='User is already in this project.'),
        ),
    ]
