# Generated by Django 6.0.2 on 2026-02-20 09:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('jira_id', models.TextField(max_length=43, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(blank=True, max_length=50, null=True)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('role', models.TextField(choices=[('SD', 'Software Developer'), ('SSD', 'Senior Software Developer'), ('QA', 'Quality Analyst'), ('M', 'manager'), ('DG', 'designer')], default='SD', max_length=3)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
