# Generated by Django 4.2.28 on 2026-03-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='jira_id',
            field=models.TextField(error_messages={'max_length': 'Not a valid jira id', 'unique': 'User with this jira id already exists'}, max_length=50, unique=True),
        ),
    ]
