# Generated by Django 4.2.28 on 2026-03-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='deadline_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
