# Generated by Django 4.2.28 on 2026-03-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notifications',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('ticket', 'subscriber', 'is_deleted'), name='uniq_active_ticket_subscription'),
        ),
    ]
